### ISSUE TITLE
Implement unbinned fits

### ISSUE THREAD

**Issue by AndrewEdmonds11** [AndrewEdmonds11/roofitter#4]
This should come after implementing the flat tree conversion. It would be great if we could add an (optional?) ability to use RooFit's unbinned fitting procedures. This would allow us to go to higher than 3 dimensions.

**Comment by sophiemiddleton** [comment]
Hi, andy, good to see the fcl update added. I am beginning to look into the unbinned fits a bit, although my time is pretty packed at the moment, keep me posted on progress ( i need to merge the upgrades before continuing)

**Comment by sophiemiddleton** [comment]
Great to see its sorted, and merged successfully, well done Leo and hope you both have a good holiday :)
